// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package edge_router_policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/netfoundry/ziti-edge/rest_model"
)

// GetEdgeRouterPoliciesIDEdgeRoutersReader is a Reader for the GetEdgeRouterPoliciesIDEdgeRouters structure.
type GetEdgeRouterPoliciesIDEdgeRoutersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetEdgeRouterPoliciesIDEdgeRoutersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetEdgeRouterPoliciesIDEdgeRoutersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetEdgeRouterPoliciesIDEdgeRoutersUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetEdgeRouterPoliciesIDEdgeRoutersNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetEdgeRouterPoliciesIDEdgeRoutersOK creates a GetEdgeRouterPoliciesIDEdgeRoutersOK with default headers values
func NewGetEdgeRouterPoliciesIDEdgeRoutersOK() *GetEdgeRouterPoliciesIDEdgeRoutersOK {
	return &GetEdgeRouterPoliciesIDEdgeRoutersOK{}
}

/*GetEdgeRouterPoliciesIDEdgeRoutersOK handles this case with default header values.

A list of edge routers
*/
type GetEdgeRouterPoliciesIDEdgeRoutersOK struct {
	Payload *rest_model.ListEdgeRoutersEnvelope
}

func (o *GetEdgeRouterPoliciesIDEdgeRoutersOK) Error() string {
	return fmt.Sprintf("[GET /edge-router-policies/{id}/edge-routers][%d] getEdgeRouterPoliciesIdEdgeRoutersOK  %+v", 200, o.Payload)
}

func (o *GetEdgeRouterPoliciesIDEdgeRoutersOK) GetPayload() *rest_model.ListEdgeRoutersEnvelope {
	return o.Payload
}

func (o *GetEdgeRouterPoliciesIDEdgeRoutersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(rest_model.ListEdgeRoutersEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetEdgeRouterPoliciesIDEdgeRoutersUnauthorized creates a GetEdgeRouterPoliciesIDEdgeRoutersUnauthorized with default headers values
func NewGetEdgeRouterPoliciesIDEdgeRoutersUnauthorized() *GetEdgeRouterPoliciesIDEdgeRoutersUnauthorized {
	return &GetEdgeRouterPoliciesIDEdgeRoutersUnauthorized{}
}

/*GetEdgeRouterPoliciesIDEdgeRoutersUnauthorized handles this case with default header values.

The currently supplied session does not have the correct access rights to request this resource
*/
type GetEdgeRouterPoliciesIDEdgeRoutersUnauthorized struct {
	Payload *rest_model.APIErrorEnvelope
}

func (o *GetEdgeRouterPoliciesIDEdgeRoutersUnauthorized) Error() string {
	return fmt.Sprintf("[GET /edge-router-policies/{id}/edge-routers][%d] getEdgeRouterPoliciesIdEdgeRoutersUnauthorized  %+v", 401, o.Payload)
}

func (o *GetEdgeRouterPoliciesIDEdgeRoutersUnauthorized) GetPayload() *rest_model.APIErrorEnvelope {
	return o.Payload
}

func (o *GetEdgeRouterPoliciesIDEdgeRoutersUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetEdgeRouterPoliciesIDEdgeRoutersNotFound creates a GetEdgeRouterPoliciesIDEdgeRoutersNotFound with default headers values
func NewGetEdgeRouterPoliciesIDEdgeRoutersNotFound() *GetEdgeRouterPoliciesIDEdgeRoutersNotFound {
	return &GetEdgeRouterPoliciesIDEdgeRoutersNotFound{}
}

/*GetEdgeRouterPoliciesIDEdgeRoutersNotFound handles this case with default header values.

The requested resource does not exist
*/
type GetEdgeRouterPoliciesIDEdgeRoutersNotFound struct {
	Payload *rest_model.APIErrorEnvelope
}

func (o *GetEdgeRouterPoliciesIDEdgeRoutersNotFound) Error() string {
	return fmt.Sprintf("[GET /edge-router-policies/{id}/edge-routers][%d] getEdgeRouterPoliciesIdEdgeRoutersNotFound  %+v", 404, o.Payload)
}

func (o *GetEdgeRouterPoliciesIDEdgeRoutersNotFound) GetPayload() *rest_model.APIErrorEnvelope {
	return o.Payload
}

func (o *GetEdgeRouterPoliciesIDEdgeRoutersNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
