// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package enroll

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostEnrollOttHandlerFunc turns a function with the right signature into a post enroll ott handler
type PostEnrollOttHandlerFunc func(PostEnrollOttParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostEnrollOttHandlerFunc) Handle(params PostEnrollOttParams) middleware.Responder {
	return fn(params)
}

// PostEnrollOttHandler interface for that can handle valid post enroll ott params
type PostEnrollOttHandler interface {
	Handle(PostEnrollOttParams) middleware.Responder
}

// NewPostEnrollOtt creates a new http.Handler for the post enroll ott operation
func NewPostEnrollOtt(ctx *middleware.Context, handler PostEnrollOttHandler) *PostEnrollOtt {
	return &PostEnrollOtt{Context: ctx, Handler: handler}
}

/*PostEnrollOtt swagger:route POST /enroll/ott Enroll postEnrollOtt

Enroll an identity via one-time-token

Enroll an identity via a one-time-token which is supplied via a query string parameter. This enrollment method
expects a PEM encoded CSRs to be provided for fulfillment. It is up to the enrolling identity to manage the
private key backing the CSR request.


*/
type PostEnrollOtt struct {
	Context *middleware.Context
	Handler PostEnrollOttHandler
}

func (o *PostEnrollOtt) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostEnrollOttParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
