// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package enroll

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostEnrollOttcaHandlerFunc turns a function with the right signature into a post enroll ottca handler
type PostEnrollOttcaHandlerFunc func(PostEnrollOttcaParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostEnrollOttcaHandlerFunc) Handle(params PostEnrollOttcaParams) middleware.Responder {
	return fn(params)
}

// PostEnrollOttcaHandler interface for that can handle valid post enroll ottca params
type PostEnrollOttcaHandler interface {
	Handle(PostEnrollOttcaParams) middleware.Responder
}

// NewPostEnrollOttca creates a new http.Handler for the post enroll ottca operation
func NewPostEnrollOttca(ctx *middleware.Context, handler PostEnrollOttcaHandler) *PostEnrollOttca {
	return &PostEnrollOttca{Context: ctx, Handler: handler}
}

/*PostEnrollOttca swagger:route POST /enroll/ottca Enroll postEnrollOttca

Enroll an identity via one-time-token with a pre-exchanged client certificate

Enroll an identity via a one-time-token that also requires a pre-exchanged client certificate to match a
Certificate Authority that has been added and verified (See POST /cas and POST /cas{id}/verify). The client
must present a client certificate signed by CA associated with the enrollment. This enrollment is similar to
CA auto enrollment except that is required the identity to be pre-created.

As the client certificat has been pre-exchanged there is no CSR input to this enrollment method.


*/
type PostEnrollOttca struct {
	Context *middleware.Context
	Handler PostEnrollOttcaHandler
}

func (o *PostEnrollOttca) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostEnrollOttcaParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
