// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package edge_router_policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetEdgeRouterPoliciesIDIdentitiesHandlerFunc turns a function with the right signature into a get edge router policies ID identities handler
type GetEdgeRouterPoliciesIDIdentitiesHandlerFunc func(GetEdgeRouterPoliciesIDIdentitiesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetEdgeRouterPoliciesIDIdentitiesHandlerFunc) Handle(params GetEdgeRouterPoliciesIDIdentitiesParams) middleware.Responder {
	return fn(params)
}

// GetEdgeRouterPoliciesIDIdentitiesHandler interface for that can handle valid get edge router policies ID identities params
type GetEdgeRouterPoliciesIDIdentitiesHandler interface {
	Handle(GetEdgeRouterPoliciesIDIdentitiesParams) middleware.Responder
}

// NewGetEdgeRouterPoliciesIDIdentities creates a new http.Handler for the get edge router policies ID identities operation
func NewGetEdgeRouterPoliciesIDIdentities(ctx *middleware.Context, handler GetEdgeRouterPoliciesIDIdentitiesHandler) *GetEdgeRouterPoliciesIDIdentities {
	return &GetEdgeRouterPoliciesIDIdentities{Context: ctx, Handler: handler}
}

/*GetEdgeRouterPoliciesIDIdentities swagger:route GET /edge-router-policies/{id}/identities Edge Router Policy getEdgeRouterPoliciesIdIdentities

List identities an edge router policy affects

Retrieves a list of identities an edge router policy resources affects; supports filtering, sorting, and pagination. Requires admin access.


*/
type GetEdgeRouterPoliciesIDIdentities struct {
	Context *middleware.Context
	Handler GetEdgeRouterPoliciesIDIdentitiesHandler
}

func (o *GetEdgeRouterPoliciesIDIdentities) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetEdgeRouterPoliciesIDIdentitiesParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
