// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package edge_router_policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/netfoundry/ziti-edge/models"
)

// GetEdgeRouterPoliciesIDEdgeRoutersOKCode is the HTTP code returned for type GetEdgeRouterPoliciesIDEdgeRoutersOK
const GetEdgeRouterPoliciesIDEdgeRoutersOKCode int = 200

/*GetEdgeRouterPoliciesIDEdgeRoutersOK A list of edge routers

swagger:response getEdgeRouterPoliciesIdEdgeRoutersOK
*/
type GetEdgeRouterPoliciesIDEdgeRoutersOK struct {

	/*
	  In: Body
	*/
	Payload *models.ListEdgeRoutersEnvelope `json:"body,omitempty"`
}

// NewGetEdgeRouterPoliciesIDEdgeRoutersOK creates GetEdgeRouterPoliciesIDEdgeRoutersOK with default headers values
func NewGetEdgeRouterPoliciesIDEdgeRoutersOK() *GetEdgeRouterPoliciesIDEdgeRoutersOK {

	return &GetEdgeRouterPoliciesIDEdgeRoutersOK{}
}

// WithPayload adds the payload to the get edge router policies Id edge routers o k response
func (o *GetEdgeRouterPoliciesIDEdgeRoutersOK) WithPayload(payload *models.ListEdgeRoutersEnvelope) *GetEdgeRouterPoliciesIDEdgeRoutersOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get edge router policies Id edge routers o k response
func (o *GetEdgeRouterPoliciesIDEdgeRoutersOK) SetPayload(payload *models.ListEdgeRoutersEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetEdgeRouterPoliciesIDEdgeRoutersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetEdgeRouterPoliciesIDEdgeRoutersUnauthorizedCode is the HTTP code returned for type GetEdgeRouterPoliciesIDEdgeRoutersUnauthorized
const GetEdgeRouterPoliciesIDEdgeRoutersUnauthorizedCode int = 401

/*GetEdgeRouterPoliciesIDEdgeRoutersUnauthorized The currently supplied session does not have the correct access rights to request this resource

swagger:response getEdgeRouterPoliciesIdEdgeRoutersUnauthorized
*/
type GetEdgeRouterPoliciesIDEdgeRoutersUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.APIErrorEnvelope `json:"body,omitempty"`
}

// NewGetEdgeRouterPoliciesIDEdgeRoutersUnauthorized creates GetEdgeRouterPoliciesIDEdgeRoutersUnauthorized with default headers values
func NewGetEdgeRouterPoliciesIDEdgeRoutersUnauthorized() *GetEdgeRouterPoliciesIDEdgeRoutersUnauthorized {

	return &GetEdgeRouterPoliciesIDEdgeRoutersUnauthorized{}
}

// WithPayload adds the payload to the get edge router policies Id edge routers unauthorized response
func (o *GetEdgeRouterPoliciesIDEdgeRoutersUnauthorized) WithPayload(payload *models.APIErrorEnvelope) *GetEdgeRouterPoliciesIDEdgeRoutersUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get edge router policies Id edge routers unauthorized response
func (o *GetEdgeRouterPoliciesIDEdgeRoutersUnauthorized) SetPayload(payload *models.APIErrorEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetEdgeRouterPoliciesIDEdgeRoutersUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetEdgeRouterPoliciesIDEdgeRoutersNotFoundCode is the HTTP code returned for type GetEdgeRouterPoliciesIDEdgeRoutersNotFound
const GetEdgeRouterPoliciesIDEdgeRoutersNotFoundCode int = 404

/*GetEdgeRouterPoliciesIDEdgeRoutersNotFound The requested resource does not exist

swagger:response getEdgeRouterPoliciesIdEdgeRoutersNotFound
*/
type GetEdgeRouterPoliciesIDEdgeRoutersNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.APIErrorEnvelope `json:"body,omitempty"`
}

// NewGetEdgeRouterPoliciesIDEdgeRoutersNotFound creates GetEdgeRouterPoliciesIDEdgeRoutersNotFound with default headers values
func NewGetEdgeRouterPoliciesIDEdgeRoutersNotFound() *GetEdgeRouterPoliciesIDEdgeRoutersNotFound {

	return &GetEdgeRouterPoliciesIDEdgeRoutersNotFound{}
}

// WithPayload adds the payload to the get edge router policies Id edge routers not found response
func (o *GetEdgeRouterPoliciesIDEdgeRoutersNotFound) WithPayload(payload *models.APIErrorEnvelope) *GetEdgeRouterPoliciesIDEdgeRoutersNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get edge router policies Id edge routers not found response
func (o *GetEdgeRouterPoliciesIDEdgeRoutersNotFound) SetPayload(payload *models.APIErrorEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetEdgeRouterPoliciesIDEdgeRoutersNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
