// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package edge_router_policy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/netfoundry/ziti-edge/rest_model"
)

// GetEdgeRouterPoliciesIDIdentitiesOKCode is the HTTP code returned for type GetEdgeRouterPoliciesIDIdentitiesOK
const GetEdgeRouterPoliciesIDIdentitiesOKCode int = 200

/*GetEdgeRouterPoliciesIDIdentitiesOK A list of identities

swagger:response getEdgeRouterPoliciesIdIdentitiesOK
*/
type GetEdgeRouterPoliciesIDIdentitiesOK struct {

	/*
	  In: Body
	*/
	Payload *rest_model.ListIdentitiesEnvelope `json:"body,omitempty"`
}

// NewGetEdgeRouterPoliciesIDIdentitiesOK creates GetEdgeRouterPoliciesIDIdentitiesOK with default headers values
func NewGetEdgeRouterPoliciesIDIdentitiesOK() *GetEdgeRouterPoliciesIDIdentitiesOK {

	return &GetEdgeRouterPoliciesIDIdentitiesOK{}
}

// WithPayload adds the payload to the get edge router policies Id identities o k response
func (o *GetEdgeRouterPoliciesIDIdentitiesOK) WithPayload(payload *rest_model.ListIdentitiesEnvelope) *GetEdgeRouterPoliciesIDIdentitiesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get edge router policies Id identities o k response
func (o *GetEdgeRouterPoliciesIDIdentitiesOK) SetPayload(payload *rest_model.ListIdentitiesEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetEdgeRouterPoliciesIDIdentitiesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetEdgeRouterPoliciesIDIdentitiesUnauthorizedCode is the HTTP code returned for type GetEdgeRouterPoliciesIDIdentitiesUnauthorized
const GetEdgeRouterPoliciesIDIdentitiesUnauthorizedCode int = 401

/*GetEdgeRouterPoliciesIDIdentitiesUnauthorized The currently supplied session does not have the correct access rights to request this resource

swagger:response getEdgeRouterPoliciesIdIdentitiesUnauthorized
*/
type GetEdgeRouterPoliciesIDIdentitiesUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *rest_model.APIErrorEnvelope `json:"body,omitempty"`
}

// NewGetEdgeRouterPoliciesIDIdentitiesUnauthorized creates GetEdgeRouterPoliciesIDIdentitiesUnauthorized with default headers values
func NewGetEdgeRouterPoliciesIDIdentitiesUnauthorized() *GetEdgeRouterPoliciesIDIdentitiesUnauthorized {

	return &GetEdgeRouterPoliciesIDIdentitiesUnauthorized{}
}

// WithPayload adds the payload to the get edge router policies Id identities unauthorized response
func (o *GetEdgeRouterPoliciesIDIdentitiesUnauthorized) WithPayload(payload *rest_model.APIErrorEnvelope) *GetEdgeRouterPoliciesIDIdentitiesUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get edge router policies Id identities unauthorized response
func (o *GetEdgeRouterPoliciesIDIdentitiesUnauthorized) SetPayload(payload *rest_model.APIErrorEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetEdgeRouterPoliciesIDIdentitiesUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetEdgeRouterPoliciesIDIdentitiesNotFoundCode is the HTTP code returned for type GetEdgeRouterPoliciesIDIdentitiesNotFound
const GetEdgeRouterPoliciesIDIdentitiesNotFoundCode int = 404

/*GetEdgeRouterPoliciesIDIdentitiesNotFound The requested resource does not exist

swagger:response getEdgeRouterPoliciesIdIdentitiesNotFound
*/
type GetEdgeRouterPoliciesIDIdentitiesNotFound struct {

	/*
	  In: Body
	*/
	Payload *rest_model.APIErrorEnvelope `json:"body,omitempty"`
}

// NewGetEdgeRouterPoliciesIDIdentitiesNotFound creates GetEdgeRouterPoliciesIDIdentitiesNotFound with default headers values
func NewGetEdgeRouterPoliciesIDIdentitiesNotFound() *GetEdgeRouterPoliciesIDIdentitiesNotFound {

	return &GetEdgeRouterPoliciesIDIdentitiesNotFound{}
}

// WithPayload adds the payload to the get edge router policies Id identities not found response
func (o *GetEdgeRouterPoliciesIDIdentitiesNotFound) WithPayload(payload *rest_model.APIErrorEnvelope) *GetEdgeRouterPoliciesIDIdentitiesNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get edge router policies Id identities not found response
func (o *GetEdgeRouterPoliciesIDIdentitiesNotFound) SetPayload(payload *rest_model.APIErrorEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetEdgeRouterPoliciesIDIdentitiesNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
