// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package edge_router

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// LisgEdgeRoutersHandlerFunc turns a function with the right signature into a lisg edge routers handler
type LisgEdgeRoutersHandlerFunc func(LisgEdgeRoutersParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn LisgEdgeRoutersHandlerFunc) Handle(params LisgEdgeRoutersParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// LisgEdgeRoutersHandler interface for that can handle valid lisg edge routers params
type LisgEdgeRoutersHandler interface {
	Handle(LisgEdgeRoutersParams, interface{}) middleware.Responder
}

// NewLisgEdgeRouters creates a new http.Handler for the lisg edge routers operation
func NewLisgEdgeRouters(ctx *middleware.Context, handler LisgEdgeRoutersHandler) *LisgEdgeRouters {
	return &LisgEdgeRouters{Context: ctx, Handler: handler}
}

/*LisgEdgeRouters swagger:route GET /edge-routers Edge Router lisgEdgeRouters

List edge routers

Retrieves a list of edge router resources; supports filtering, sorting, and pagination. Requires admin access.


*/
type LisgEdgeRouters struct {
	Context *middleware.Context
	Handler LisgEdgeRoutersHandler
}

func (o *LisgEdgeRouters) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewLisgEdgeRoutersParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
