// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package edge_router

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/netfoundry/ziti-edge/rest_model"
)

// ListEdgeRouterServicePoliciesOKCode is the HTTP code returned for type ListEdgeRouterServicePoliciesOK
const ListEdgeRouterServicePoliciesOKCode int = 200

/*ListEdgeRouterServicePoliciesOK A list of service policies

swagger:response listEdgeRouterServicePoliciesOK
*/
type ListEdgeRouterServicePoliciesOK struct {

	/*
	  In: Body
	*/
	Payload *rest_model.ListServicePoliciesEnvelope `json:"body,omitempty"`
}

// NewListEdgeRouterServicePoliciesOK creates ListEdgeRouterServicePoliciesOK with default headers values
func NewListEdgeRouterServicePoliciesOK() *ListEdgeRouterServicePoliciesOK {

	return &ListEdgeRouterServicePoliciesOK{}
}

// WithPayload adds the payload to the list edge router service policies o k response
func (o *ListEdgeRouterServicePoliciesOK) WithPayload(payload *rest_model.ListServicePoliciesEnvelope) *ListEdgeRouterServicePoliciesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list edge router service policies o k response
func (o *ListEdgeRouterServicePoliciesOK) SetPayload(payload *rest_model.ListServicePoliciesEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListEdgeRouterServicePoliciesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListEdgeRouterServicePoliciesUnauthorizedCode is the HTTP code returned for type ListEdgeRouterServicePoliciesUnauthorized
const ListEdgeRouterServicePoliciesUnauthorizedCode int = 401

/*ListEdgeRouterServicePoliciesUnauthorized The currently supplied session does not have the correct access rights to request this resource

swagger:response listEdgeRouterServicePoliciesUnauthorized
*/
type ListEdgeRouterServicePoliciesUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *rest_model.APIErrorEnvelope `json:"body,omitempty"`
}

// NewListEdgeRouterServicePoliciesUnauthorized creates ListEdgeRouterServicePoliciesUnauthorized with default headers values
func NewListEdgeRouterServicePoliciesUnauthorized() *ListEdgeRouterServicePoliciesUnauthorized {

	return &ListEdgeRouterServicePoliciesUnauthorized{}
}

// WithPayload adds the payload to the list edge router service policies unauthorized response
func (o *ListEdgeRouterServicePoliciesUnauthorized) WithPayload(payload *rest_model.APIErrorEnvelope) *ListEdgeRouterServicePoliciesUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list edge router service policies unauthorized response
func (o *ListEdgeRouterServicePoliciesUnauthorized) SetPayload(payload *rest_model.APIErrorEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListEdgeRouterServicePoliciesUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListEdgeRouterServicePoliciesNotFoundCode is the HTTP code returned for type ListEdgeRouterServicePoliciesNotFound
const ListEdgeRouterServicePoliciesNotFoundCode int = 404

/*ListEdgeRouterServicePoliciesNotFound The requested resource does not exist

swagger:response listEdgeRouterServicePoliciesNotFound
*/
type ListEdgeRouterServicePoliciesNotFound struct {

	/*
	  In: Body
	*/
	Payload *rest_model.APIErrorEnvelope `json:"body,omitempty"`
}

// NewListEdgeRouterServicePoliciesNotFound creates ListEdgeRouterServicePoliciesNotFound with default headers values
func NewListEdgeRouterServicePoliciesNotFound() *ListEdgeRouterServicePoliciesNotFound {

	return &ListEdgeRouterServicePoliciesNotFound{}
}

// WithPayload adds the payload to the list edge router service policies not found response
func (o *ListEdgeRouterServicePoliciesNotFound) WithPayload(payload *rest_model.APIErrorEnvelope) *ListEdgeRouterServicePoliciesNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list edge router service policies not found response
func (o *ListEdgeRouterServicePoliciesNotFound) SetPayload(payload *rest_model.APIErrorEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListEdgeRouterServicePoliciesNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
