// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package edge_router

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/netfoundry/ziti-edge/models"
)

// ListEdgeRoutersEdgeRouterPoliciesOKCode is the HTTP code returned for type ListEdgeRoutersEdgeRouterPoliciesOK
const ListEdgeRoutersEdgeRouterPoliciesOKCode int = 200

/*ListEdgeRoutersEdgeRouterPoliciesOK A list of edge router policies

swagger:response listEdgeRoutersEdgeRouterPoliciesOK
*/
type ListEdgeRoutersEdgeRouterPoliciesOK struct {

	/*
	  In: Body
	*/
	Payload *models.ListEdgeRouterPoliciesEnvelope `json:"body,omitempty"`
}

// NewListEdgeRoutersEdgeRouterPoliciesOK creates ListEdgeRoutersEdgeRouterPoliciesOK with default headers values
func NewListEdgeRoutersEdgeRouterPoliciesOK() *ListEdgeRoutersEdgeRouterPoliciesOK {

	return &ListEdgeRoutersEdgeRouterPoliciesOK{}
}

// WithPayload adds the payload to the list edge routers edge router policies o k response
func (o *ListEdgeRoutersEdgeRouterPoliciesOK) WithPayload(payload *models.ListEdgeRouterPoliciesEnvelope) *ListEdgeRoutersEdgeRouterPoliciesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list edge routers edge router policies o k response
func (o *ListEdgeRoutersEdgeRouterPoliciesOK) SetPayload(payload *models.ListEdgeRouterPoliciesEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListEdgeRoutersEdgeRouterPoliciesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListEdgeRoutersEdgeRouterPoliciesUnauthorizedCode is the HTTP code returned for type ListEdgeRoutersEdgeRouterPoliciesUnauthorized
const ListEdgeRoutersEdgeRouterPoliciesUnauthorizedCode int = 401

/*ListEdgeRoutersEdgeRouterPoliciesUnauthorized The currently supplied session does not have the correct access rights to request this resource

swagger:response listEdgeRoutersEdgeRouterPoliciesUnauthorized
*/
type ListEdgeRoutersEdgeRouterPoliciesUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.APIErrorEnvelope `json:"body,omitempty"`
}

// NewListEdgeRoutersEdgeRouterPoliciesUnauthorized creates ListEdgeRoutersEdgeRouterPoliciesUnauthorized with default headers values
func NewListEdgeRoutersEdgeRouterPoliciesUnauthorized() *ListEdgeRoutersEdgeRouterPoliciesUnauthorized {

	return &ListEdgeRoutersEdgeRouterPoliciesUnauthorized{}
}

// WithPayload adds the payload to the list edge routers edge router policies unauthorized response
func (o *ListEdgeRoutersEdgeRouterPoliciesUnauthorized) WithPayload(payload *models.APIErrorEnvelope) *ListEdgeRoutersEdgeRouterPoliciesUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list edge routers edge router policies unauthorized response
func (o *ListEdgeRoutersEdgeRouterPoliciesUnauthorized) SetPayload(payload *models.APIErrorEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListEdgeRoutersEdgeRouterPoliciesUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListEdgeRoutersEdgeRouterPoliciesNotFoundCode is the HTTP code returned for type ListEdgeRoutersEdgeRouterPoliciesNotFound
const ListEdgeRoutersEdgeRouterPoliciesNotFoundCode int = 404

/*ListEdgeRoutersEdgeRouterPoliciesNotFound The requested resource does not exist

swagger:response listEdgeRoutersEdgeRouterPoliciesNotFound
*/
type ListEdgeRoutersEdgeRouterPoliciesNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.APIErrorEnvelope `json:"body,omitempty"`
}

// NewListEdgeRoutersEdgeRouterPoliciesNotFound creates ListEdgeRoutersEdgeRouterPoliciesNotFound with default headers values
func NewListEdgeRoutersEdgeRouterPoliciesNotFound() *ListEdgeRoutersEdgeRouterPoliciesNotFound {

	return &ListEdgeRoutersEdgeRouterPoliciesNotFound{}
}

// WithPayload adds the payload to the list edge routers edge router policies not found response
func (o *ListEdgeRoutersEdgeRouterPoliciesNotFound) WithPayload(payload *models.APIErrorEnvelope) *ListEdgeRoutersEdgeRouterPoliciesNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list edge routers edge router policies not found response
func (o *ListEdgeRoutersEdgeRouterPoliciesNotFound) SetPayload(payload *models.APIErrorEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListEdgeRoutersEdgeRouterPoliciesNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
