// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package edge_router

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/netfoundry/ziti-edge/models"
)

// ListEdgeRoutersServicePoliciesOKCode is the HTTP code returned for type ListEdgeRoutersServicePoliciesOK
const ListEdgeRoutersServicePoliciesOKCode int = 200

/*ListEdgeRoutersServicePoliciesOK A list of service policies

swagger:response listEdgeRoutersServicePoliciesOK
*/
type ListEdgeRoutersServicePoliciesOK struct {

	/*
	  In: Body
	*/
	Payload *models.ListServicePoliciesEnvelope `json:"body,omitempty"`
}

// NewListEdgeRoutersServicePoliciesOK creates ListEdgeRoutersServicePoliciesOK with default headers values
func NewListEdgeRoutersServicePoliciesOK() *ListEdgeRoutersServicePoliciesOK {

	return &ListEdgeRoutersServicePoliciesOK{}
}

// WithPayload adds the payload to the list edge routers service policies o k response
func (o *ListEdgeRoutersServicePoliciesOK) WithPayload(payload *models.ListServicePoliciesEnvelope) *ListEdgeRoutersServicePoliciesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list edge routers service policies o k response
func (o *ListEdgeRoutersServicePoliciesOK) SetPayload(payload *models.ListServicePoliciesEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListEdgeRoutersServicePoliciesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListEdgeRoutersServicePoliciesUnauthorizedCode is the HTTP code returned for type ListEdgeRoutersServicePoliciesUnauthorized
const ListEdgeRoutersServicePoliciesUnauthorizedCode int = 401

/*ListEdgeRoutersServicePoliciesUnauthorized The currently supplied session does not have the correct access rights to request this resource

swagger:response listEdgeRoutersServicePoliciesUnauthorized
*/
type ListEdgeRoutersServicePoliciesUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.APIErrorEnvelope `json:"body,omitempty"`
}

// NewListEdgeRoutersServicePoliciesUnauthorized creates ListEdgeRoutersServicePoliciesUnauthorized with default headers values
func NewListEdgeRoutersServicePoliciesUnauthorized() *ListEdgeRoutersServicePoliciesUnauthorized {

	return &ListEdgeRoutersServicePoliciesUnauthorized{}
}

// WithPayload adds the payload to the list edge routers service policies unauthorized response
func (o *ListEdgeRoutersServicePoliciesUnauthorized) WithPayload(payload *models.APIErrorEnvelope) *ListEdgeRoutersServicePoliciesUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list edge routers service policies unauthorized response
func (o *ListEdgeRoutersServicePoliciesUnauthorized) SetPayload(payload *models.APIErrorEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListEdgeRoutersServicePoliciesUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListEdgeRoutersServicePoliciesNotFoundCode is the HTTP code returned for type ListEdgeRoutersServicePoliciesNotFound
const ListEdgeRoutersServicePoliciesNotFoundCode int = 404

/*ListEdgeRoutersServicePoliciesNotFound The requested resource does not exist

swagger:response listEdgeRoutersServicePoliciesNotFound
*/
type ListEdgeRoutersServicePoliciesNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.APIErrorEnvelope `json:"body,omitempty"`
}

// NewListEdgeRoutersServicePoliciesNotFound creates ListEdgeRoutersServicePoliciesNotFound with default headers values
func NewListEdgeRoutersServicePoliciesNotFound() *ListEdgeRoutersServicePoliciesNotFound {

	return &ListEdgeRoutersServicePoliciesNotFound{}
}

// WithPayload adds the payload to the list edge routers service policies not found response
func (o *ListEdgeRoutersServicePoliciesNotFound) WithPayload(payload *models.APIErrorEnvelope) *ListEdgeRoutersServicePoliciesNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list edge routers service policies not found response
func (o *ListEdgeRoutersServicePoliciesNotFound) SetPayload(payload *models.APIErrorEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListEdgeRoutersServicePoliciesNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
