// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package rest_model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// IdentityPatch identity patch
//
// swagger:model identityPatch
type IdentityPatch struct {

	// is admin
	IsAdmin bool `json:"isAdmin,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// type
	// Enum: [User Device Service]
	Type string `json:"type,omitempty"`
}

// Validate validates this identity patch
func (m *IdentityPatch) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var identityPatchTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["User","Device","Service"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		identityPatchTypeTypePropEnum = append(identityPatchTypeTypePropEnum, v)
	}
}

const (

	// IdentityPatchTypeUser captures enum value "User"
	IdentityPatchTypeUser string = "User"

	// IdentityPatchTypeDevice captures enum value "Device"
	IdentityPatchTypeDevice string = "Device"

	// IdentityPatchTypeService captures enum value "Service"
	IdentityPatchTypeService string = "Service"
)

// prop value enum
func (m *IdentityPatch) validateTypeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, identityPatchTypeTypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *IdentityPatch) validateType(formats strfmt.Registry) error {

	if swag.IsZero(m.Type) { // not required
		return nil
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *IdentityPatch) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IdentityPatch) UnmarshalBinary(b []byte) error {
	var res IdentityPatch
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
