// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package rest_model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// IdentityUpdate identity update
//
// swagger:model identityUpdate
type IdentityUpdate struct {

	// is admin
	// Required: true
	IsAdmin *bool `json:"isAdmin"`

	// name
	// Required: true
	Name *string `json:"name"`

	// tags
	// Required: true
	Tags Tags `json:"tags"`

	// type
	// Required: true
	// Enum: [User Device Service]
	Type *string `json:"type"`
}

// Validate validates this identity update
func (m *IdentityUpdate) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateIsAdmin(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTags(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IdentityUpdate) validateIsAdmin(formats strfmt.Registry) error {

	if err := validate.Required("isAdmin", "body", m.IsAdmin); err != nil {
		return err
	}

	return nil
}

func (m *IdentityUpdate) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *IdentityUpdate) validateTags(formats strfmt.Registry) error {

	if err := m.Tags.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("tags")
		}
		return err
	}

	return nil
}

var identityUpdateTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["User","Device","Service"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		identityUpdateTypeTypePropEnum = append(identityUpdateTypeTypePropEnum, v)
	}
}

const (

	// IdentityUpdateTypeUser captures enum value "User"
	IdentityUpdateTypeUser string = "User"

	// IdentityUpdateTypeDevice captures enum value "Device"
	IdentityUpdateTypeDevice string = "Device"

	// IdentityUpdateTypeService captures enum value "Service"
	IdentityUpdateTypeService string = "Service"
)

// prop value enum
func (m *IdentityUpdate) validateTypeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, identityUpdateTypeTypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *IdentityUpdate) validateType(formats strfmt.Registry) error {

	if err := validate.Required("type", "body", m.Type); err != nil {
		return err
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", *m.Type); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *IdentityUpdate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IdentityUpdate) UnmarshalBinary(b []byte) error {
	var res IdentityUpdate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
