// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package certificate_authority

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/netfoundry/ziti-edge/models"
)

// GetCasIDJwtReader is a Reader for the GetCasIDJwt structure.
type GetCasIDJwtReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCasIDJwtReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetCasIDJwtOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetCasIDJwtUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetCasIDJwtNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetCasIDJwtOK creates a GetCasIDJwtOK with default headers values
func NewGetCasIDJwtOK() *GetCasIDJwtOK {
	return &GetCasIDJwtOK{}
}

/*GetCasIDJwtOK handles this case with default header values.

The result is the JWT text to validate the CA
*/
type GetCasIDJwtOK struct {
	Payload string
}

func (o *GetCasIDJwtOK) Error() string {
	return fmt.Sprintf("[GET /cas/{id}/jwt][%d] getCasIdJwtOK  %+v", 200, o.Payload)
}

func (o *GetCasIDJwtOK) GetPayload() string {
	return o.Payload
}

func (o *GetCasIDJwtOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCasIDJwtUnauthorized creates a GetCasIDJwtUnauthorized with default headers values
func NewGetCasIDJwtUnauthorized() *GetCasIDJwtUnauthorized {
	return &GetCasIDJwtUnauthorized{}
}

/*GetCasIDJwtUnauthorized handles this case with default header values.

The currently supplied session does not have the correct access rights to request this resource
*/
type GetCasIDJwtUnauthorized struct {
	Payload *models.APIErrorEnvelope
}

func (o *GetCasIDJwtUnauthorized) Error() string {
	return fmt.Sprintf("[GET /cas/{id}/jwt][%d] getCasIdJwtUnauthorized  %+v", 401, o.Payload)
}

func (o *GetCasIDJwtUnauthorized) GetPayload() *models.APIErrorEnvelope {
	return o.Payload
}

func (o *GetCasIDJwtUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCasIDJwtNotFound creates a GetCasIDJwtNotFound with default headers values
func NewGetCasIDJwtNotFound() *GetCasIDJwtNotFound {
	return &GetCasIDJwtNotFound{}
}

/*GetCasIDJwtNotFound handles this case with default header values.

The requested resource does not exist
*/
type GetCasIDJwtNotFound struct {
	Payload *models.APIErrorEnvelope
}

func (o *GetCasIDJwtNotFound) Error() string {
	return fmt.Sprintf("[GET /cas/{id}/jwt][%d] getCasIdJwtNotFound  %+v", 404, o.Payload)
}

func (o *GetCasIDJwtNotFound) GetPayload() *models.APIErrorEnvelope {
	return o.Payload
}

func (o *GetCasIDJwtNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
