// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package authenticator

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/netfoundry/ziti-edge/rest_model"
)

// NewCreateAuthenticatorsParams creates a new CreateAuthenticatorsParams object
// with the default values initialized.
func NewCreateAuthenticatorsParams() *CreateAuthenticatorsParams {
	var ()
	return &CreateAuthenticatorsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateAuthenticatorsParamsWithTimeout creates a new CreateAuthenticatorsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateAuthenticatorsParamsWithTimeout(timeout time.Duration) *CreateAuthenticatorsParams {
	var ()
	return &CreateAuthenticatorsParams{

		timeout: timeout,
	}
}

// NewCreateAuthenticatorsParamsWithContext creates a new CreateAuthenticatorsParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateAuthenticatorsParamsWithContext(ctx context.Context) *CreateAuthenticatorsParams {
	var ()
	return &CreateAuthenticatorsParams{

		Context: ctx,
	}
}

// NewCreateAuthenticatorsParamsWithHTTPClient creates a new CreateAuthenticatorsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateAuthenticatorsParamsWithHTTPClient(client *http.Client) *CreateAuthenticatorsParams {
	var ()
	return &CreateAuthenticatorsParams{
		HTTPClient: client,
	}
}

/*CreateAuthenticatorsParams contains all the parameters to send to the API endpoint
for the create authenticators operation typically these are written to a http.Request
*/
type CreateAuthenticatorsParams struct {

	/*Body
	  A Authenticators create object

	*/
	Body *rest_model.AuthenticatorCreate

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create authenticators params
func (o *CreateAuthenticatorsParams) WithTimeout(timeout time.Duration) *CreateAuthenticatorsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create authenticators params
func (o *CreateAuthenticatorsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create authenticators params
func (o *CreateAuthenticatorsParams) WithContext(ctx context.Context) *CreateAuthenticatorsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create authenticators params
func (o *CreateAuthenticatorsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create authenticators params
func (o *CreateAuthenticatorsParams) WithHTTPClient(client *http.Client) *CreateAuthenticatorsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create authenticators params
func (o *CreateAuthenticatorsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create authenticators params
func (o *CreateAuthenticatorsParams) WithBody(body *rest_model.AuthenticatorCreate) *CreateAuthenticatorsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create authenticators params
func (o *CreateAuthenticatorsParams) SetBody(body *rest_model.AuthenticatorCreate) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateAuthenticatorsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
