// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package authenticator

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/netfoundry/ziti-edge/rest_model"
)

// CreateAuthenticatorsReader is a Reader for the CreateAuthenticators structure.
type CreateAuthenticatorsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateAuthenticatorsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateAuthenticatorsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateAuthenticatorsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewCreateAuthenticatorsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateAuthenticatorsOK creates a CreateAuthenticatorsOK with default headers values
func NewCreateAuthenticatorsOK() *CreateAuthenticatorsOK {
	return &CreateAuthenticatorsOK{}
}

/*CreateAuthenticatorsOK handles this case with default header values.

The create was successful
*/
type CreateAuthenticatorsOK struct {
	Payload *rest_model.AuthenticatorCreate
}

func (o *CreateAuthenticatorsOK) Error() string {
	return fmt.Sprintf("[POST /authenticators][%d] createAuthenticatorsOK  %+v", 200, o.Payload)
}

func (o *CreateAuthenticatorsOK) GetPayload() *rest_model.AuthenticatorCreate {
	return o.Payload
}

func (o *CreateAuthenticatorsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(rest_model.AuthenticatorCreate)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateAuthenticatorsBadRequest creates a CreateAuthenticatorsBadRequest with default headers values
func NewCreateAuthenticatorsBadRequest() *CreateAuthenticatorsBadRequest {
	return &CreateAuthenticatorsBadRequest{}
}

/*CreateAuthenticatorsBadRequest handles this case with default header values.

The supplied request contains invalid fields or could not be parsed (json and non-json bodies). The error's code, message, and cause fields can be inspected for further information
*/
type CreateAuthenticatorsBadRequest struct {
	Payload *rest_model.APIErrorEnvelope
}

func (o *CreateAuthenticatorsBadRequest) Error() string {
	return fmt.Sprintf("[POST /authenticators][%d] createAuthenticatorsBadRequest  %+v", 400, o.Payload)
}

func (o *CreateAuthenticatorsBadRequest) GetPayload() *rest_model.APIErrorEnvelope {
	return o.Payload
}

func (o *CreateAuthenticatorsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateAuthenticatorsUnauthorized creates a CreateAuthenticatorsUnauthorized with default headers values
func NewCreateAuthenticatorsUnauthorized() *CreateAuthenticatorsUnauthorized {
	return &CreateAuthenticatorsUnauthorized{}
}

/*CreateAuthenticatorsUnauthorized handles this case with default header values.

The currently supplied session does not have the correct access rights to request this resource
*/
type CreateAuthenticatorsUnauthorized struct {
	Payload *rest_model.APIErrorEnvelope
}

func (o *CreateAuthenticatorsUnauthorized) Error() string {
	return fmt.Sprintf("[POST /authenticators][%d] createAuthenticatorsUnauthorized  %+v", 401, o.Payload)
}

func (o *CreateAuthenticatorsUnauthorized) GetPayload() *rest_model.APIErrorEnvelope {
	return o.Payload
}

func (o *CreateAuthenticatorsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
