// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/netfoundry/ziti-edge/rest_model"
)

// ListConfigOKCode is the HTTP code returned for type ListConfigOK
const ListConfigOKCode int = 200

/*ListConfigOK A list of configs

swagger:response listConfigOK
*/
type ListConfigOK struct {

	/*
	  In: Body
	*/
	Payload *rest_model.ListConfigsEnvelope `json:"body,omitempty"`
}

// NewListConfigOK creates ListConfigOK with default headers values
func NewListConfigOK() *ListConfigOK {

	return &ListConfigOK{}
}

// WithPayload adds the payload to the list config o k response
func (o *ListConfigOK) WithPayload(payload *rest_model.ListConfigsEnvelope) *ListConfigOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list config o k response
func (o *ListConfigOK) SetPayload(payload *rest_model.ListConfigsEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListConfigOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListConfigUnauthorizedCode is the HTTP code returned for type ListConfigUnauthorized
const ListConfigUnauthorizedCode int = 401

/*ListConfigUnauthorized The currently supplied session does not have the correct access rights to request this resource

swagger:response listConfigUnauthorized
*/
type ListConfigUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *rest_model.APIErrorEnvelope `json:"body,omitempty"`
}

// NewListConfigUnauthorized creates ListConfigUnauthorized with default headers values
func NewListConfigUnauthorized() *ListConfigUnauthorized {

	return &ListConfigUnauthorized{}
}

// WithPayload adds the payload to the list config unauthorized response
func (o *ListConfigUnauthorized) WithPayload(payload *rest_model.APIErrorEnvelope) *ListConfigUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list config unauthorized response
func (o *ListConfigUnauthorized) SetPayload(payload *rest_model.APIErrorEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListConfigUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
