// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package ca

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/netfoundry/ziti-edge/models"
)

// CreateCAOKCode is the HTTP code returned for type CreateCAOK
const CreateCAOKCode int = 200

/*CreateCAOK The create request was successful and the resource has been added at the following location

swagger:response createCaOK
*/
type CreateCAOK struct {

	/*
	  In: Body
	*/
	Payload *models.Create `json:"body,omitempty"`
}

// NewCreateCAOK creates CreateCAOK with default headers values
func NewCreateCAOK() *CreateCAOK {

	return &CreateCAOK{}
}

// WithPayload adds the payload to the create Ca o k response
func (o *CreateCAOK) WithPayload(payload *models.Create) *CreateCAOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create Ca o k response
func (o *CreateCAOK) SetPayload(payload *models.Create) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateCAOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateCABadRequestCode is the HTTP code returned for type CreateCABadRequest
const CreateCABadRequestCode int = 400

/*CreateCABadRequest The supplied request contains invalid fields or could not be parsed (json and non-json bodies). The error's code, message, and cause fields can be inspected for further information

swagger:response createCaBadRequest
*/
type CreateCABadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.APIErrorEnvelope `json:"body,omitempty"`
}

// NewCreateCABadRequest creates CreateCABadRequest with default headers values
func NewCreateCABadRequest() *CreateCABadRequest {

	return &CreateCABadRequest{}
}

// WithPayload adds the payload to the create Ca bad request response
func (o *CreateCABadRequest) WithPayload(payload *models.APIErrorEnvelope) *CreateCABadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create Ca bad request response
func (o *CreateCABadRequest) SetPayload(payload *models.APIErrorEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateCABadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateCAUnauthorizedCode is the HTTP code returned for type CreateCAUnauthorized
const CreateCAUnauthorizedCode int = 401

/*CreateCAUnauthorized The currently supplied session does not have the correct access rights to request this resource

swagger:response createCaUnauthorized
*/
type CreateCAUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.APIErrorEnvelope `json:"body,omitempty"`
}

// NewCreateCAUnauthorized creates CreateCAUnauthorized with default headers values
func NewCreateCAUnauthorized() *CreateCAUnauthorized {

	return &CreateCAUnauthorized{}
}

// WithPayload adds the payload to the create Ca unauthorized response
func (o *CreateCAUnauthorized) WithPayload(payload *models.APIErrorEnvelope) *CreateCAUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create Ca unauthorized response
func (o *CreateCAUnauthorized) SetPayload(payload *models.APIErrorEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateCAUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
