// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package ca

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/netfoundry/ziti-edge/models"
)

// DetailCAOKCode is the HTTP code returned for type DetailCAOK
const DetailCAOKCode int = 200

/*DetailCAOK A singular Certificate Authority (CA) resource

swagger:response detailCaOK
*/
type DetailCAOK struct {

	/*
	  In: Body
	*/
	Payload *models.DetailCAEnvelope `json:"body,omitempty"`
}

// NewDetailCAOK creates DetailCAOK with default headers values
func NewDetailCAOK() *DetailCAOK {

	return &DetailCAOK{}
}

// WithPayload adds the payload to the detail Ca o k response
func (o *DetailCAOK) WithPayload(payload *models.DetailCAEnvelope) *DetailCAOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the detail Ca o k response
func (o *DetailCAOK) SetPayload(payload *models.DetailCAEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DetailCAOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DetailCAUnauthorizedCode is the HTTP code returned for type DetailCAUnauthorized
const DetailCAUnauthorizedCode int = 401

/*DetailCAUnauthorized The currently supplied session does not have the correct access rights to request this resource

swagger:response detailCaUnauthorized
*/
type DetailCAUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.APIErrorEnvelope `json:"body,omitempty"`
}

// NewDetailCAUnauthorized creates DetailCAUnauthorized with default headers values
func NewDetailCAUnauthorized() *DetailCAUnauthorized {

	return &DetailCAUnauthorized{}
}

// WithPayload adds the payload to the detail Ca unauthorized response
func (o *DetailCAUnauthorized) WithPayload(payload *models.APIErrorEnvelope) *DetailCAUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the detail Ca unauthorized response
func (o *DetailCAUnauthorized) SetPayload(payload *models.APIErrorEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DetailCAUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DetailCANotFoundCode is the HTTP code returned for type DetailCANotFound
const DetailCANotFoundCode int = 404

/*DetailCANotFound The requested resource does not exist

swagger:response detailCaNotFound
*/
type DetailCANotFound struct {

	/*
	  In: Body
	*/
	Payload *models.APIErrorEnvelope `json:"body,omitempty"`
}

// NewDetailCANotFound creates DetailCANotFound with default headers values
func NewDetailCANotFound() *DetailCANotFound {

	return &DetailCANotFound{}
}

// WithPayload adds the payload to the detail Ca not found response
func (o *DetailCANotFound) WithPayload(payload *models.APIErrorEnvelope) *DetailCANotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the detail Ca not found response
func (o *DetailCANotFound) SetPayload(payload *models.APIErrorEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DetailCANotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
