// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package identity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/netfoundry/ziti-edge/rest_model"
)

// ListIdentityTypeOKCode is the HTTP code returned for type ListIdentityTypeOK
const ListIdentityTypeOKCode int = 200

/*ListIdentityTypeOK A list of identity types

swagger:response listIdentityTypeOK
*/
type ListIdentityTypeOK struct {

	/*
	  In: Body
	*/
	Payload *rest_model.ListIdentityTypesEnvelope `json:"body,omitempty"`
}

// NewListIdentityTypeOK creates ListIdentityTypeOK with default headers values
func NewListIdentityTypeOK() *ListIdentityTypeOK {

	return &ListIdentityTypeOK{}
}

// WithPayload adds the payload to the list identity type o k response
func (o *ListIdentityTypeOK) WithPayload(payload *rest_model.ListIdentityTypesEnvelope) *ListIdentityTypeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list identity type o k response
func (o *ListIdentityTypeOK) SetPayload(payload *rest_model.ListIdentityTypesEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListIdentityTypeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListIdentityTypeUnauthorizedCode is the HTTP code returned for type ListIdentityTypeUnauthorized
const ListIdentityTypeUnauthorizedCode int = 401

/*ListIdentityTypeUnauthorized The currently supplied session does not have the correct access rights to request this resource

swagger:response listIdentityTypeUnauthorized
*/
type ListIdentityTypeUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *rest_model.APIErrorEnvelope `json:"body,omitempty"`
}

// NewListIdentityTypeUnauthorized creates ListIdentityTypeUnauthorized with default headers values
func NewListIdentityTypeUnauthorized() *ListIdentityTypeUnauthorized {

	return &ListIdentityTypeUnauthorized{}
}

// WithPayload adds the payload to the list identity type unauthorized response
func (o *ListIdentityTypeUnauthorized) WithPayload(payload *rest_model.APIErrorEnvelope) *ListIdentityTypeUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list identity type unauthorized response
func (o *ListIdentityTypeUnauthorized) SetPayload(payload *rest_model.APIErrorEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListIdentityTypeUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
