// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package identity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/netfoundry/ziti-edge/models"
)

// ListIdentityServicePoliciesOKCode is the HTTP code returned for type ListIdentityServicePoliciesOK
const ListIdentityServicePoliciesOKCode int = 200

/*ListIdentityServicePoliciesOK A list of service policies

swagger:response listIdentityServicePoliciesOK
*/
type ListIdentityServicePoliciesOK struct {

	/*
	  In: Body
	*/
	Payload *models.ListServicePoliciesEnvelope `json:"body,omitempty"`
}

// NewListIdentityServicePoliciesOK creates ListIdentityServicePoliciesOK with default headers values
func NewListIdentityServicePoliciesOK() *ListIdentityServicePoliciesOK {

	return &ListIdentityServicePoliciesOK{}
}

// WithPayload adds the payload to the list identity service policies o k response
func (o *ListIdentityServicePoliciesOK) WithPayload(payload *models.ListServicePoliciesEnvelope) *ListIdentityServicePoliciesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list identity service policies o k response
func (o *ListIdentityServicePoliciesOK) SetPayload(payload *models.ListServicePoliciesEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListIdentityServicePoliciesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListIdentityServicePoliciesUnauthorizedCode is the HTTP code returned for type ListIdentityServicePoliciesUnauthorized
const ListIdentityServicePoliciesUnauthorizedCode int = 401

/*ListIdentityServicePoliciesUnauthorized The currently supplied session does not have the correct access rights to request this resource

swagger:response listIdentityServicePoliciesUnauthorized
*/
type ListIdentityServicePoliciesUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.APIErrorEnvelope `json:"body,omitempty"`
}

// NewListIdentityServicePoliciesUnauthorized creates ListIdentityServicePoliciesUnauthorized with default headers values
func NewListIdentityServicePoliciesUnauthorized() *ListIdentityServicePoliciesUnauthorized {

	return &ListIdentityServicePoliciesUnauthorized{}
}

// WithPayload adds the payload to the list identity service policies unauthorized response
func (o *ListIdentityServicePoliciesUnauthorized) WithPayload(payload *models.APIErrorEnvelope) *ListIdentityServicePoliciesUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list identity service policies unauthorized response
func (o *ListIdentityServicePoliciesUnauthorized) SetPayload(payload *models.APIErrorEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListIdentityServicePoliciesUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListIdentityServicePoliciesNotFoundCode is the HTTP code returned for type ListIdentityServicePoliciesNotFound
const ListIdentityServicePoliciesNotFoundCode int = 404

/*ListIdentityServicePoliciesNotFound The requested resource does not exist

swagger:response listIdentityServicePoliciesNotFound
*/
type ListIdentityServicePoliciesNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.APIErrorEnvelope `json:"body,omitempty"`
}

// NewListIdentityServicePoliciesNotFound creates ListIdentityServicePoliciesNotFound with default headers values
func NewListIdentityServicePoliciesNotFound() *ListIdentityServicePoliciesNotFound {

	return &ListIdentityServicePoliciesNotFound{}
}

// WithPayload adds the payload to the list identity service policies not found response
func (o *ListIdentityServicePoliciesNotFound) WithPayload(payload *models.APIErrorEnvelope) *ListIdentityServicePoliciesNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list identity service policies not found response
func (o *ListIdentityServicePoliciesNotFound) SetPayload(payload *models.APIErrorEnvelope) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListIdentityServicePoliciesNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
