// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package identity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListIdentityTypeHandlerFunc turns a function with the right signature into a list identity type handler
type ListIdentityTypeHandlerFunc func(ListIdentityTypeParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ListIdentityTypeHandlerFunc) Handle(params ListIdentityTypeParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ListIdentityTypeHandler interface for that can handle valid list identity type params
type ListIdentityTypeHandler interface {
	Handle(ListIdentityTypeParams, interface{}) middleware.Responder
}

// NewListIdentityType creates a new http.Handler for the list identity type operation
func NewListIdentityType(ctx *middleware.Context, handler ListIdentityTypeHandler) *ListIdentityType {
	return &ListIdentityType{Context: ctx, Handler: handler}
}

/*ListIdentityType swagger:route GET /identity-types Identity listIdentityType

List available identity types

Retrieves a list of identity types; supports filtering, sorting, and pagination. Requires admin access.


*/
type ListIdentityType struct {
	Context *middleware.Context
	Handler ListIdentityTypeHandler
}

func (o *ListIdentityType) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewListIdentityTypeParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
