// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package edge_router

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/netfoundry/ziti-edge/models"
)

// LisgEdgeRoutersReader is a Reader for the LisgEdgeRouters structure.
type LisgEdgeRoutersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LisgEdgeRoutersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewLisgEdgeRoutersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewLisgEdgeRoutersUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewLisgEdgeRoutersOK creates a LisgEdgeRoutersOK with default headers values
func NewLisgEdgeRoutersOK() *LisgEdgeRoutersOK {
	return &LisgEdgeRoutersOK{}
}

/*LisgEdgeRoutersOK handles this case with default header values.

A list of edge routers
*/
type LisgEdgeRoutersOK struct {
	Payload *models.ListEdgeRoutersEnvelope
}

func (o *LisgEdgeRoutersOK) Error() string {
	return fmt.Sprintf("[GET /edge-routers][%d] lisgEdgeRoutersOK  %+v", 200, o.Payload)
}

func (o *LisgEdgeRoutersOK) GetPayload() *models.ListEdgeRoutersEnvelope {
	return o.Payload
}

func (o *LisgEdgeRoutersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ListEdgeRoutersEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewLisgEdgeRoutersUnauthorized creates a LisgEdgeRoutersUnauthorized with default headers values
func NewLisgEdgeRoutersUnauthorized() *LisgEdgeRoutersUnauthorized {
	return &LisgEdgeRoutersUnauthorized{}
}

/*LisgEdgeRoutersUnauthorized handles this case with default header values.

The currently supplied session does not have the correct access rights to request this resource
*/
type LisgEdgeRoutersUnauthorized struct {
	Payload *models.APIErrorEnvelope
}

func (o *LisgEdgeRoutersUnauthorized) Error() string {
	return fmt.Sprintf("[GET /edge-routers][%d] lisgEdgeRoutersUnauthorized  %+v", 401, o.Payload)
}

func (o *LisgEdgeRoutersUnauthorized) GetPayload() *models.APIErrorEnvelope {
	return o.Payload
}

func (o *LisgEdgeRoutersUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
