// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package edge_router

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/netfoundry/ziti-edge/models"
)

// ListEdgeRoutersEdgeRouterPoliciesReader is a Reader for the ListEdgeRoutersEdgeRouterPolicies structure.
type ListEdgeRoutersEdgeRouterPoliciesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListEdgeRoutersEdgeRouterPoliciesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListEdgeRoutersEdgeRouterPoliciesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewListEdgeRoutersEdgeRouterPoliciesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewListEdgeRoutersEdgeRouterPoliciesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListEdgeRoutersEdgeRouterPoliciesOK creates a ListEdgeRoutersEdgeRouterPoliciesOK with default headers values
func NewListEdgeRoutersEdgeRouterPoliciesOK() *ListEdgeRoutersEdgeRouterPoliciesOK {
	return &ListEdgeRoutersEdgeRouterPoliciesOK{}
}

/*ListEdgeRoutersEdgeRouterPoliciesOK handles this case with default header values.

A list of edge router policies
*/
type ListEdgeRoutersEdgeRouterPoliciesOK struct {
	Payload *models.ListEdgeRouterPoliciesEnvelope
}

func (o *ListEdgeRoutersEdgeRouterPoliciesOK) Error() string {
	return fmt.Sprintf("[GET /edge-routers/{id}/edge-router-policies][%d] listEdgeRoutersEdgeRouterPoliciesOK  %+v", 200, o.Payload)
}

func (o *ListEdgeRoutersEdgeRouterPoliciesOK) GetPayload() *models.ListEdgeRouterPoliciesEnvelope {
	return o.Payload
}

func (o *ListEdgeRoutersEdgeRouterPoliciesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ListEdgeRouterPoliciesEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListEdgeRoutersEdgeRouterPoliciesUnauthorized creates a ListEdgeRoutersEdgeRouterPoliciesUnauthorized with default headers values
func NewListEdgeRoutersEdgeRouterPoliciesUnauthorized() *ListEdgeRoutersEdgeRouterPoliciesUnauthorized {
	return &ListEdgeRoutersEdgeRouterPoliciesUnauthorized{}
}

/*ListEdgeRoutersEdgeRouterPoliciesUnauthorized handles this case with default header values.

The currently supplied session does not have the correct access rights to request this resource
*/
type ListEdgeRoutersEdgeRouterPoliciesUnauthorized struct {
	Payload *models.APIErrorEnvelope
}

func (o *ListEdgeRoutersEdgeRouterPoliciesUnauthorized) Error() string {
	return fmt.Sprintf("[GET /edge-routers/{id}/edge-router-policies][%d] listEdgeRoutersEdgeRouterPoliciesUnauthorized  %+v", 401, o.Payload)
}

func (o *ListEdgeRoutersEdgeRouterPoliciesUnauthorized) GetPayload() *models.APIErrorEnvelope {
	return o.Payload
}

func (o *ListEdgeRoutersEdgeRouterPoliciesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListEdgeRoutersEdgeRouterPoliciesNotFound creates a ListEdgeRoutersEdgeRouterPoliciesNotFound with default headers values
func NewListEdgeRoutersEdgeRouterPoliciesNotFound() *ListEdgeRoutersEdgeRouterPoliciesNotFound {
	return &ListEdgeRoutersEdgeRouterPoliciesNotFound{}
}

/*ListEdgeRoutersEdgeRouterPoliciesNotFound handles this case with default header values.

The requested resource does not exist
*/
type ListEdgeRoutersEdgeRouterPoliciesNotFound struct {
	Payload *models.APIErrorEnvelope
}

func (o *ListEdgeRoutersEdgeRouterPoliciesNotFound) Error() string {
	return fmt.Sprintf("[GET /edge-routers/{id}/edge-router-policies][%d] listEdgeRoutersEdgeRouterPoliciesNotFound  %+v", 404, o.Payload)
}

func (o *ListEdgeRoutersEdgeRouterPoliciesNotFound) GetPayload() *models.APIErrorEnvelope {
	return o.Payload
}

func (o *ListEdgeRoutersEdgeRouterPoliciesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
