// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package edge_router

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/netfoundry/ziti-edge/rest_model"
)

// ListEdgeRouterServicePoliciesReader is a Reader for the ListEdgeRouterServicePolicies structure.
type ListEdgeRouterServicePoliciesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListEdgeRouterServicePoliciesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListEdgeRouterServicePoliciesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewListEdgeRouterServicePoliciesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewListEdgeRouterServicePoliciesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListEdgeRouterServicePoliciesOK creates a ListEdgeRouterServicePoliciesOK with default headers values
func NewListEdgeRouterServicePoliciesOK() *ListEdgeRouterServicePoliciesOK {
	return &ListEdgeRouterServicePoliciesOK{}
}

/*ListEdgeRouterServicePoliciesOK handles this case with default header values.

A list of service policies
*/
type ListEdgeRouterServicePoliciesOK struct {
	Payload *rest_model.ListServicePoliciesEnvelope
}

func (o *ListEdgeRouterServicePoliciesOK) Error() string {
	return fmt.Sprintf("[GET /edge-routers/{id}/service-edge-router-policies][%d] listEdgeRouterServicePoliciesOK  %+v", 200, o.Payload)
}

func (o *ListEdgeRouterServicePoliciesOK) GetPayload() *rest_model.ListServicePoliciesEnvelope {
	return o.Payload
}

func (o *ListEdgeRouterServicePoliciesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(rest_model.ListServicePoliciesEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListEdgeRouterServicePoliciesUnauthorized creates a ListEdgeRouterServicePoliciesUnauthorized with default headers values
func NewListEdgeRouterServicePoliciesUnauthorized() *ListEdgeRouterServicePoliciesUnauthorized {
	return &ListEdgeRouterServicePoliciesUnauthorized{}
}

/*ListEdgeRouterServicePoliciesUnauthorized handles this case with default header values.

The currently supplied session does not have the correct access rights to request this resource
*/
type ListEdgeRouterServicePoliciesUnauthorized struct {
	Payload *rest_model.APIErrorEnvelope
}

func (o *ListEdgeRouterServicePoliciesUnauthorized) Error() string {
	return fmt.Sprintf("[GET /edge-routers/{id}/service-edge-router-policies][%d] listEdgeRouterServicePoliciesUnauthorized  %+v", 401, o.Payload)
}

func (o *ListEdgeRouterServicePoliciesUnauthorized) GetPayload() *rest_model.APIErrorEnvelope {
	return o.Payload
}

func (o *ListEdgeRouterServicePoliciesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListEdgeRouterServicePoliciesNotFound creates a ListEdgeRouterServicePoliciesNotFound with default headers values
func NewListEdgeRouterServicePoliciesNotFound() *ListEdgeRouterServicePoliciesNotFound {
	return &ListEdgeRouterServicePoliciesNotFound{}
}

/*ListEdgeRouterServicePoliciesNotFound handles this case with default header values.

The requested resource does not exist
*/
type ListEdgeRouterServicePoliciesNotFound struct {
	Payload *rest_model.APIErrorEnvelope
}

func (o *ListEdgeRouterServicePoliciesNotFound) Error() string {
	return fmt.Sprintf("[GET /edge-routers/{id}/service-edge-router-policies][%d] listEdgeRouterServicePoliciesNotFound  %+v", 404, o.Payload)
}

func (o *ListEdgeRouterServicePoliciesNotFound) GetPayload() *rest_model.APIErrorEnvelope {
	return o.Payload
}

func (o *ListEdgeRouterServicePoliciesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(rest_model.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
