// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package enroll

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostEnrollUpdbParams creates a new PostEnrollUpdbParams object
// with the default values initialized.
func NewPostEnrollUpdbParams() *PostEnrollUpdbParams {
	var ()
	return &PostEnrollUpdbParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostEnrollUpdbParamsWithTimeout creates a new PostEnrollUpdbParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostEnrollUpdbParamsWithTimeout(timeout time.Duration) *PostEnrollUpdbParams {
	var ()
	return &PostEnrollUpdbParams{

		timeout: timeout,
	}
}

// NewPostEnrollUpdbParamsWithContext creates a new PostEnrollUpdbParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostEnrollUpdbParamsWithContext(ctx context.Context) *PostEnrollUpdbParams {
	var ()
	return &PostEnrollUpdbParams{

		Context: ctx,
	}
}

// NewPostEnrollUpdbParamsWithHTTPClient creates a new PostEnrollUpdbParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPostEnrollUpdbParamsWithHTTPClient(client *http.Client) *PostEnrollUpdbParams {
	var ()
	return &PostEnrollUpdbParams{
		HTTPClient: client,
	}
}

/*PostEnrollUpdbParams contains all the parameters to send to the API endpoint
for the post enroll updb operation typically these are written to a http.Request
*/
type PostEnrollUpdbParams struct {

	/*Token*/
	Token strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post enroll updb params
func (o *PostEnrollUpdbParams) WithTimeout(timeout time.Duration) *PostEnrollUpdbParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post enroll updb params
func (o *PostEnrollUpdbParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post enroll updb params
func (o *PostEnrollUpdbParams) WithContext(ctx context.Context) *PostEnrollUpdbParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post enroll updb params
func (o *PostEnrollUpdbParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post enroll updb params
func (o *PostEnrollUpdbParams) WithHTTPClient(client *http.Client) *PostEnrollUpdbParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post enroll updb params
func (o *PostEnrollUpdbParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithToken adds the token to the post enroll updb params
func (o *PostEnrollUpdbParams) WithToken(token strfmt.UUID) *PostEnrollUpdbParams {
	o.SetToken(token)
	return o
}

// SetToken adds the token to the post enroll updb params
func (o *PostEnrollUpdbParams) SetToken(token strfmt.UUID) {
	o.Token = token
}

// WriteToRequest writes these params to a swagger request
func (o *PostEnrollUpdbParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param token
	qrToken := o.Token
	qToken := qrToken.String()
	if qToken != "" {
		if err := r.SetQueryParam("token", qToken); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
