// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package authenticator

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateAuthenticatorsHandlerFunc turns a function with the right signature into a create authenticators handler
type CreateAuthenticatorsHandlerFunc func(CreateAuthenticatorsParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateAuthenticatorsHandlerFunc) Handle(params CreateAuthenticatorsParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// CreateAuthenticatorsHandler interface for that can handle valid create authenticators params
type CreateAuthenticatorsHandler interface {
	Handle(CreateAuthenticatorsParams, interface{}) middleware.Responder
}

// NewCreateAuthenticators creates a new http.Handler for the create authenticators operation
func NewCreateAuthenticators(ctx *middleware.Context, handler CreateAuthenticatorsHandler) *CreateAuthenticators {
	return &CreateAuthenticators{Context: ctx, Handler: handler}
}

/*CreateAuthenticators swagger:route POST /authenticators Authenticator createAuthenticators

Creates an authenticator

Creates an authenticator for a specific identity. Requires admin access.


*/
type CreateAuthenticators struct {
	Context *middleware.Context
	Handler CreateAuthenticatorsHandler
}

func (o *CreateAuthenticators) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateAuthenticatorsParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
