// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package ca

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new ca API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for ca API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	GetCasIDJwt(params *GetCasIDJwtParams, authInfo runtime.ClientAuthInfoWriter) (*GetCasIDJwtOK, error)

	PostCasIDVerify(params *PostCasIDVerifyParams, authInfo runtime.ClientAuthInfoWriter) (*PostCasIDVerifyOK, error)

	CreateCA(params *CreateCAParams, authInfo runtime.ClientAuthInfoWriter) (*CreateCAOK, error)

	DeleteCA(params *DeleteCAParams, authInfo runtime.ClientAuthInfoWriter) (*DeleteCAOK, error)

	DetailCA(params *DetailCAParams, authInfo runtime.ClientAuthInfoWriter) (*DetailCAOK, error)

	ListCA(params *ListCAParams, authInfo runtime.ClientAuthInfoWriter) (*ListCAOK, error)

	PatchCA(params *PatchCAParams, authInfo runtime.ClientAuthInfoWriter) (*PatchCAOK, error)

	UpdateCA(params *UpdateCAParams, authInfo runtime.ClientAuthInfoWriter) (*UpdateCAOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  GetCasIDJwt retrieves the enrollment j w t for a CA

  For CA auto enrollment, the enrollment JWT is static and provided on each CA resource. This endpoint provides
the jwt as a text response.

*/
func (a *Client) GetCasIDJwt(params *GetCasIDJwtParams, authInfo runtime.ClientAuthInfoWriter) (*GetCasIDJwtOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetCasIDJwtParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetCasIDJwt",
		Method:             "GET",
		PathPattern:        "/cas/{id}/jwt",
		ProducesMediaTypes: []string{"application/jwt"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetCasIDJwtReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetCasIDJwtOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetCasIDJwt: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  PostCasIDVerify verifies a CA

  Allows a CA to become verified by submitting a certificate in PEM format that has been signed by the target CA.
The common name on the certificate must match the verificationToken property of the CA. Unverfieid CAs can not
be used for enrollment/authentication. Requires admin access.

*/
func (a *Client) PostCasIDVerify(params *PostCasIDVerifyParams, authInfo runtime.ClientAuthInfoWriter) (*PostCasIDVerifyOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostCasIDVerifyParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "PostCasIDVerify",
		Method:             "POST",
		PathPattern:        "/cas/{id}/verify",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"text/plain"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PostCasIDVerifyReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PostCasIDVerifyOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for PostCasIDVerify: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  CreateCA creates a CA

  Creates a CA in an unverified state. Requires admin access.
*/
func (a *Client) CreateCA(params *CreateCAParams, authInfo runtime.ClientAuthInfoWriter) (*CreateCAOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateCAParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "createCA",
		Method:             "POST",
		PathPattern:        "/cas",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CreateCAReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CreateCAOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for createCA: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  DeleteCA deletes a CA

  Delete a CA by id. Deleting a CA will delete its associated certificate authenticators. This can make it
impossible for identities to authenticate if they no longer have any valid authenticators. Requires admin access.

*/
func (a *Client) DeleteCA(params *DeleteCAParams, authInfo runtime.ClientAuthInfoWriter) (*DeleteCAOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteCAParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "deleteCA",
		Method:             "DELETE",
		PathPattern:        "/cas/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DeleteCAReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeleteCAOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for deleteCA: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  DetailCA retrieves a single CA

  Retrieves a single CA by id. Requires admin access.
*/
func (a *Client) DetailCA(params *DetailCAParams, authInfo runtime.ClientAuthInfoWriter) (*DetailCAOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDetailCAParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "detailCA",
		Method:             "GET",
		PathPattern:        "/cas/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DetailCAReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DetailCAOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for detailCA: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  ListCA lists c as

  Retrieves a list of CA resources; supports filtering, sorting, and pagination. Requires admin access.
*/
func (a *Client) ListCA(params *ListCAParams, authInfo runtime.ClientAuthInfoWriter) (*ListCAOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListCAParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "listCA",
		Method:             "GET",
		PathPattern:        "/cas",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ListCAReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ListCAOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for listCA: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  PatchCA updates the supplied fields on a CA

  Update only the supplied fields on a CA by id. Requires admin access.
*/
func (a *Client) PatchCA(params *PatchCAParams, authInfo runtime.ClientAuthInfoWriter) (*PatchCAOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPatchCAParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "patchCA",
		Method:             "PATCH",
		PathPattern:        "/cas/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PatchCAReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PatchCAOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for patchCA: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  UpdateCA updates all fields on a CA

  Update all fields on a CA by id. Requires admin access.
*/
func (a *Client) UpdateCA(params *UpdateCAParams, authInfo runtime.ClientAuthInfoWriter) (*UpdateCAOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUpdateCAParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "updateCA",
		Method:             "PUT",
		PathPattern:        "/cas/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &UpdateCAReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*UpdateCAOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for updateCA: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
