// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package ca

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/netfoundry/ziti-edge/models"
)

// NewCreateCAParams creates a new CreateCAParams object
// with the default values initialized.
func NewCreateCAParams() *CreateCAParams {
	var ()
	return &CreateCAParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateCAParamsWithTimeout creates a new CreateCAParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateCAParamsWithTimeout(timeout time.Duration) *CreateCAParams {
	var ()
	return &CreateCAParams{

		timeout: timeout,
	}
}

// NewCreateCAParamsWithContext creates a new CreateCAParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateCAParamsWithContext(ctx context.Context) *CreateCAParams {
	var ()
	return &CreateCAParams{

		Context: ctx,
	}
}

// NewCreateCAParamsWithHTTPClient creates a new CreateCAParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateCAParamsWithHTTPClient(client *http.Client) *CreateCAParams {
	var ()
	return &CreateCAParams{
		HTTPClient: client,
	}
}

/*CreateCAParams contains all the parameters to send to the API endpoint
for the create CA operation typically these are written to a http.Request
*/
type CreateCAParams struct {

	/*Body
	  A CA to create

	*/
	Body *models.CACreate

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create CA params
func (o *CreateCAParams) WithTimeout(timeout time.Duration) *CreateCAParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create CA params
func (o *CreateCAParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create CA params
func (o *CreateCAParams) WithContext(ctx context.Context) *CreateCAParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create CA params
func (o *CreateCAParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create CA params
func (o *CreateCAParams) WithHTTPClient(client *http.Client) *CreateCAParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create CA params
func (o *CreateCAParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create CA params
func (o *CreateCAParams) WithBody(body *models.CACreate) *CreateCAParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create CA params
func (o *CreateCAParams) SetBody(body *models.CACreate) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateCAParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
