// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package ca

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/netfoundry/ziti-edge/models"
)

// DeleteCAReader is a Reader for the DeleteCA structure.
type DeleteCAReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteCAReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteCAOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteCABadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteCAUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteCAOK creates a DeleteCAOK with default headers values
func NewDeleteCAOK() *DeleteCAOK {
	return &DeleteCAOK{}
}

/*DeleteCAOK handles this case with default header values.

The delete request was successful and the resource has been removed
*/
type DeleteCAOK struct {
	Payload *models.Empty
}

func (o *DeleteCAOK) Error() string {
	return fmt.Sprintf("[DELETE /cas/{id}][%d] deleteCaOK  %+v", 200, o.Payload)
}

func (o *DeleteCAOK) GetPayload() *models.Empty {
	return o.Payload
}

func (o *DeleteCAOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Empty)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteCABadRequest creates a DeleteCABadRequest with default headers values
func NewDeleteCABadRequest() *DeleteCABadRequest {
	return &DeleteCABadRequest{}
}

/*DeleteCABadRequest handles this case with default header values.

The supplied request contains invalid fields or could not be parsed (json and non-json bodies). The error's code, message, and cause fields can be inspected for further information
*/
type DeleteCABadRequest struct {
	Payload *models.APIErrorEnvelope
}

func (o *DeleteCABadRequest) Error() string {
	return fmt.Sprintf("[DELETE /cas/{id}][%d] deleteCaBadRequest  %+v", 400, o.Payload)
}

func (o *DeleteCABadRequest) GetPayload() *models.APIErrorEnvelope {
	return o.Payload
}

func (o *DeleteCABadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteCAUnauthorized creates a DeleteCAUnauthorized with default headers values
func NewDeleteCAUnauthorized() *DeleteCAUnauthorized {
	return &DeleteCAUnauthorized{}
}

/*DeleteCAUnauthorized handles this case with default header values.

The currently supplied session does not have the correct access rights to request this resource
*/
type DeleteCAUnauthorized struct {
	Payload *models.APIErrorEnvelope
}

func (o *DeleteCAUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /cas/{id}][%d] deleteCaUnauthorized  %+v", 401, o.Payload)
}

func (o *DeleteCAUnauthorized) GetPayload() *models.APIErrorEnvelope {
	return o.Payload
}

func (o *DeleteCAUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
