// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package ca

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/netfoundry/ziti-edge/models"
)

// DetailCAReader is a Reader for the DetailCA structure.
type DetailCAReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DetailCAReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDetailCAOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDetailCAUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDetailCANotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDetailCAOK creates a DetailCAOK with default headers values
func NewDetailCAOK() *DetailCAOK {
	return &DetailCAOK{}
}

/*DetailCAOK handles this case with default header values.

A singular Certificate Authority (CA) resource
*/
type DetailCAOK struct {
	Payload *models.DetailCAEnvelope
}

func (o *DetailCAOK) Error() string {
	return fmt.Sprintf("[GET /cas/{id}][%d] detailCaOK  %+v", 200, o.Payload)
}

func (o *DetailCAOK) GetPayload() *models.DetailCAEnvelope {
	return o.Payload
}

func (o *DetailCAOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DetailCAEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDetailCAUnauthorized creates a DetailCAUnauthorized with default headers values
func NewDetailCAUnauthorized() *DetailCAUnauthorized {
	return &DetailCAUnauthorized{}
}

/*DetailCAUnauthorized handles this case with default header values.

The currently supplied session does not have the correct access rights to request this resource
*/
type DetailCAUnauthorized struct {
	Payload *models.APIErrorEnvelope
}

func (o *DetailCAUnauthorized) Error() string {
	return fmt.Sprintf("[GET /cas/{id}][%d] detailCaUnauthorized  %+v", 401, o.Payload)
}

func (o *DetailCAUnauthorized) GetPayload() *models.APIErrorEnvelope {
	return o.Payload
}

func (o *DetailCAUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDetailCANotFound creates a DetailCANotFound with default headers values
func NewDetailCANotFound() *DetailCANotFound {
	return &DetailCANotFound{}
}

/*DetailCANotFound handles this case with default header values.

The requested resource does not exist
*/
type DetailCANotFound struct {
	Payload *models.APIErrorEnvelope
}

func (o *DetailCANotFound) Error() string {
	return fmt.Sprintf("[GET /cas/{id}][%d] detailCaNotFound  %+v", 404, o.Payload)
}

func (o *DetailCANotFound) GetPayload() *models.APIErrorEnvelope {
	return o.Payload
}

func (o *DetailCANotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
