// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package ca

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/netfoundry/ziti-edge/models"
)

// PatchCAReader is a Reader for the PatchCA structure.
type PatchCAReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchCAReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPatchCAOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPatchCABadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPatchCAUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPatchCANotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPatchCAOK creates a PatchCAOK with default headers values
func NewPatchCAOK() *PatchCAOK {
	return &PatchCAOK{}
}

/*PatchCAOK handles this case with default header values.

The patch request was successful and the resource has been altered
*/
type PatchCAOK struct {
	Payload *models.Empty
}

func (o *PatchCAOK) Error() string {
	return fmt.Sprintf("[PATCH /cas/{id}][%d] patchCaOK  %+v", 200, o.Payload)
}

func (o *PatchCAOK) GetPayload() *models.Empty {
	return o.Payload
}

func (o *PatchCAOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Empty)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPatchCABadRequest creates a PatchCABadRequest with default headers values
func NewPatchCABadRequest() *PatchCABadRequest {
	return &PatchCABadRequest{}
}

/*PatchCABadRequest handles this case with default header values.

The supplied request contains invalid fields or could not be parsed (json and non-json bodies). The error's code, message, and cause fields can be inspected for further information
*/
type PatchCABadRequest struct {
	Payload *models.APIErrorEnvelope
}

func (o *PatchCABadRequest) Error() string {
	return fmt.Sprintf("[PATCH /cas/{id}][%d] patchCaBadRequest  %+v", 400, o.Payload)
}

func (o *PatchCABadRequest) GetPayload() *models.APIErrorEnvelope {
	return o.Payload
}

func (o *PatchCABadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPatchCAUnauthorized creates a PatchCAUnauthorized with default headers values
func NewPatchCAUnauthorized() *PatchCAUnauthorized {
	return &PatchCAUnauthorized{}
}

/*PatchCAUnauthorized handles this case with default header values.

The currently supplied session does not have the correct access rights to request this resource
*/
type PatchCAUnauthorized struct {
	Payload *models.APIErrorEnvelope
}

func (o *PatchCAUnauthorized) Error() string {
	return fmt.Sprintf("[PATCH /cas/{id}][%d] patchCaUnauthorized  %+v", 401, o.Payload)
}

func (o *PatchCAUnauthorized) GetPayload() *models.APIErrorEnvelope {
	return o.Payload
}

func (o *PatchCAUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPatchCANotFound creates a PatchCANotFound with default headers values
func NewPatchCANotFound() *PatchCANotFound {
	return &PatchCANotFound{}
}

/*PatchCANotFound handles this case with default header values.

The requested resource does not exist
*/
type PatchCANotFound struct {
	Payload *models.APIErrorEnvelope
}

func (o *PatchCANotFound) Error() string {
	return fmt.Sprintf("[PATCH /cas/{id}][%d] patchCaNotFound  %+v", 404, o.Payload)
}

func (o *PatchCANotFound) GetPayload() *models.APIErrorEnvelope {
	return o.Payload
}

func (o *PatchCANotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
