// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package ca

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/netfoundry/ziti-edge/models"
)

// UpdateCAReader is a Reader for the UpdateCA structure.
type UpdateCAReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateCAReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateCAOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdateCABadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewUpdateCAUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUpdateCANotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateCAOK creates a UpdateCAOK with default headers values
func NewUpdateCAOK() *UpdateCAOK {
	return &UpdateCAOK{}
}

/*UpdateCAOK handles this case with default header values.

The update request was successful and the resource has been altered
*/
type UpdateCAOK struct {
	Payload *models.Empty
}

func (o *UpdateCAOK) Error() string {
	return fmt.Sprintf("[PUT /cas/{id}][%d] updateCaOK  %+v", 200, o.Payload)
}

func (o *UpdateCAOK) GetPayload() *models.Empty {
	return o.Payload
}

func (o *UpdateCAOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Empty)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateCABadRequest creates a UpdateCABadRequest with default headers values
func NewUpdateCABadRequest() *UpdateCABadRequest {
	return &UpdateCABadRequest{}
}

/*UpdateCABadRequest handles this case with default header values.

The supplied request contains invalid fields or could not be parsed (json and non-json bodies). The error's code, message, and cause fields can be inspected for further information
*/
type UpdateCABadRequest struct {
	Payload *models.APIErrorEnvelope
}

func (o *UpdateCABadRequest) Error() string {
	return fmt.Sprintf("[PUT /cas/{id}][%d] updateCaBadRequest  %+v", 400, o.Payload)
}

func (o *UpdateCABadRequest) GetPayload() *models.APIErrorEnvelope {
	return o.Payload
}

func (o *UpdateCABadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateCAUnauthorized creates a UpdateCAUnauthorized with default headers values
func NewUpdateCAUnauthorized() *UpdateCAUnauthorized {
	return &UpdateCAUnauthorized{}
}

/*UpdateCAUnauthorized handles this case with default header values.

The currently supplied session does not have the correct access rights to request this resource
*/
type UpdateCAUnauthorized struct {
	Payload *models.APIErrorEnvelope
}

func (o *UpdateCAUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /cas/{id}][%d] updateCaUnauthorized  %+v", 401, o.Payload)
}

func (o *UpdateCAUnauthorized) GetPayload() *models.APIErrorEnvelope {
	return o.Payload
}

func (o *UpdateCAUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateCANotFound creates a UpdateCANotFound with default headers values
func NewUpdateCANotFound() *UpdateCANotFound {
	return &UpdateCANotFound{}
}

/*UpdateCANotFound handles this case with default header values.

The requested resource does not exist
*/
type UpdateCANotFound struct {
	Payload *models.APIErrorEnvelope
}

func (o *UpdateCANotFound) Error() string {
	return fmt.Sprintf("[PUT /cas/{id}][%d] updateCaNotFound  %+v", 404, o.Payload)
}

func (o *UpdateCANotFound) GetPayload() *models.APIErrorEnvelope {
	return o.Payload
}

func (o *UpdateCANotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIErrorEnvelope)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
