// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright NetFoundry, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// __          __              _
// \ \        / /             (_)
//  \ \  /\  / /_ _ _ __ _ __  _ _ __   __ _
//   \ \/  \/ / _` | '__| '_ \| | '_ \ / _` |
//    \  /\  / (_| | |  | | | | | | | | (_| | : This file is generated, do not edit it.
//     \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |
//                                      __/ |
//                                     |___/

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TerminatorDetail terminator detail
//
// swagger:model terminatorDetail
type TerminatorDetail struct {
	BaseEntity

	// address
	Address string `json:"address,omitempty"`

	// binding
	Binding string `json:"binding,omitempty"`

	// router
	Router *EntityRef `json:"router,omitempty"`

	// router Id
	RouterID string `json:"routerId,omitempty"`

	// service
	Service *EntityRef `json:"service,omitempty"`

	// service Id
	ServiceID string `json:"serviceId,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *TerminatorDetail) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 BaseEntity
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.BaseEntity = aO0

	// AO1
	var dataAO1 struct {
		Address string `json:"address,omitempty"`

		Binding string `json:"binding,omitempty"`

		Router *EntityRef `json:"router,omitempty"`

		RouterID string `json:"routerId,omitempty"`

		Service *EntityRef `json:"service,omitempty"`

		ServiceID string `json:"serviceId,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	m.Address = dataAO1.Address

	m.Binding = dataAO1.Binding

	m.Router = dataAO1.Router

	m.RouterID = dataAO1.RouterID

	m.Service = dataAO1.Service

	m.ServiceID = dataAO1.ServiceID

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m TerminatorDetail) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.BaseEntity)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)
	var dataAO1 struct {
		Address string `json:"address,omitempty"`

		Binding string `json:"binding,omitempty"`

		Router *EntityRef `json:"router,omitempty"`

		RouterID string `json:"routerId,omitempty"`

		Service *EntityRef `json:"service,omitempty"`

		ServiceID string `json:"serviceId,omitempty"`
	}

	dataAO1.Address = m.Address

	dataAO1.Binding = m.Binding

	dataAO1.Router = m.Router

	dataAO1.RouterID = m.RouterID

	dataAO1.Service = m.Service

	dataAO1.ServiceID = m.ServiceID

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this terminator detail
func (m *TerminatorDetail) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with BaseEntity
	if err := m.BaseEntity.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRouter(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateService(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TerminatorDetail) validateRouter(formats strfmt.Registry) error {

	if swag.IsZero(m.Router) { // not required
		return nil
	}

	if m.Router != nil {
		if err := m.Router.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("router")
			}
			return err
		}
	}

	return nil
}

func (m *TerminatorDetail) validateService(formats strfmt.Registry) error {

	if swag.IsZero(m.Service) { // not required
		return nil
	}

	if m.Service != nil {
		if err := m.Service.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("service")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TerminatorDetail) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TerminatorDetail) UnmarshalBinary(b []byte) error {
	var res TerminatorDetail
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
